const perform = async (z, bundle) => {
  const options = {
    url: 'https://{{bundle.authData.subdomain}}.paycor.com/v1/employees',
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Accept: 'application/json',
      Authorization: 'Bearer {{bundle.authData.access_token}}',
      'Ocp-Apim-Subscription-Key': '{{bundle.authData.subscription_key}}',
    },
    body: {
      LegalEntityId: '{{bundle.authData.legal_entity_id}}',
      EmployeeNumber: '{{bundle.inputData.EmployeeNumber}}',
      AlternateEmployeeNumber: '{{bundle.inputData.AlternateEmployeeNumber}}',
      Prefix: '{{bundle.inputData.Prefix}}',
      FirstName: '{{bundle.inputData.FirstName}}',
      MiddleName: '{{bundle.inputData.MiddleName}}',
      LastName: '{{bundle.inputData.LastName}}',
      Suffix: '{{bundle.inputData.Suffix}}',
      HomeEmail: '{{bundle.inputData.HomeEmail}}',
      WorkEmail: '{{bundle.inputData.WorkEmail}}',
      Phones: [],
      SocialSecurityNumber: '{{bundle.inputData.SocialSecurityNumber}}',
      BirthDate: '{{bundle.inputData.BirthDate}}',
      Gender: '{{bundle.inputData.Gender}}',
      Ethnicity: '{{bundle.inputData.Ethnicity}}',
      MaritalStatus: '{{bundle.inputData.MaritalStatus}}',
      WorkLocation: '{{bundle.inputData.WorkLocation}}',
      JobTitle: '{{bundle.inputData.JobTitle}}',
      HireDate: '{{bundle.inputData.HireDate}}',
      ReHireDate: '{{bundle.inputData.ReHireDate}}',
      Status: '{{bundle.inputData.Status}}',
      Flsa: '{{bundle.inputData.Flsa}}',
      Type: '{{bundle.inputData.EmploymentType}}',
      ManagerEmpId: '{{bundle.inputData.ManagerEmpId}}',
      PaygroupDescription: '{{bundle.inputData.PaygroupDescription}}',
      DepartmentCode: '{{bundle.inputData.DepartmentCode}}',
      Veteran: '{{bundle.inputData.Veteran}}',
      Disability: '{{bundle.inputData.Disability}}',
      PrimaryAddress: {
        StreetLine1: '{{bundle.inputData.StreetLine1}}',
        StreetLine2: '{{bundle.inputData.StreetLine2}}',
        Suite: '{{bundle.inputData.Suite}}',
        City: '{{bundle.inputData.City}}',
        State: '{{bundle.inputData.State}}',
        ZipCode: '{{bundle.inputData.ZipCode}}',
        County: '{{bundle.inputData.County}}',
        Country: '{{bundle.inputData.Country}}',
      }
    },
  };
  
  if (bundle.inputData.HomePhone) {
    // remove all non-numeric values
    const homePhone = bundle.inputData.HomePhone.replace(/\D/g,'');

    options.body.Phones.push({
      CountryCode: "+1",
      AreaCode: homePhone.substr(0,3),
      PhoneNumber: `${ homePhone.substr(3,3) }-${ homePhone.substr(6,4) }`,
      Type: "Home"
    });
  }

  if (bundle.inputData.MobilePhone) {
    // remove all non-numeric values
    const mobilePhone = bundle.inputData.MobilePhone.replace(/\D/g,'');

    options.body.Phones.push({
      CountryCode: "+1",
      AreaCode: mobilePhone.substr(0,3),
      PhoneNumber: `${ mobilePhone.substr(3,3) }-${ mobilePhone.substr(6,4) }`,
      Type: "Mobile"
    });  
  }

  return z.request(options).then((response) => {
    response.throwForStatus();
    const results = response.json;
    return results.ResourceUrl;
  });
};

module.exports = {
  operation: {
    perform: perform,
    inputFields: [
      {
        key: 'EmployeeNumber',
        label: 'Employee #',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
        helpText: 'Unique number of the employee in the tenant. Generated by Paycor if not provided.'
      },
      {
        key: 'AlternateEmployeeNumber',
        label: 'Alternate Employee #',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
        helpText: 'Can be up to 10 numbers, Requires Alternate Employee Number product offering.'
      },
      {
        key: 'Prefix',
        label: 'Prefix',
        type: 'string',
        choices: ['None','Dr','DrWithSpace','Fr','Miss','Mr','Mrs','Ms','Prof','Rev','Sr'],
        helpText: 'Name prefix',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'FirstName',
        label: 'First Name',
        type: 'string',
        required: true,
        list: false,
        altersDynamicFields: false,
        helpText: 'First name of the employee.'
      },
      {
        key: 'MiddleName',
        label: 'Middle Name',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
        helpText: 'Middle name of the employee.'
      },
      {
        key: 'LastName',
        label: 'Last Name',
        type: 'string',
        required: true,
        list: false,
        altersDynamicFields: false,
        helpText: 'Last name of the employee.'
      },
      {
        key: 'Suffix',
        label: 'Suffix',
        type: 'string',
        choices: ["None","II","III","IV","V","VI","VII","VIII","IX","X","Jr","Sr"],
        helpText: 'Name Suffix',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'BirthDate',
        label: 'Birth Date',
        type: 'datetime',
        default: 'today',
        required: false,
        list: false,
        altersDynamicFields: false,
        helpText: 'Date of birth of the employee following the ISO 8601 standard.'
      },
      {
        key: 'Gender',
        label: 'Gender',
        type: 'string',
        choices: ['Male','Female'],
        helpText: "The employee's gender.",
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'Ethnicity',
        label: 'Ethnicity',
        type: 'string',
        choices: ["AmerIndorAKNative","Asian","BlackorAfricanAmerican","HispanicorLatino","White","NatHIorOthPacIsland","TwoormoreRaces","DeclinedToIdentify"],
        helpText: "The employee's ethnicity.",
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'SocialSecurityNumber',
        label: 'Social Security #',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
        helpText: 'Social Security number of the employee.'
      },
      {
        key: 'MaritalStatus',
        label: 'Marital Status',
        type: 'string',
        choices: ["Single","Married","Divorced","Separated","StateRecognizedUnion","Widowed"],
        helpText: "The employee's marital status.",
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'Veteran',
        label: 'Veteran',
        type: 'string',
        choices: ["Yes","No","DeclinedToIdentify"],
        required: false,
        list: false,
        altersDynamicFields: false,
        helpText: 'Veteran types'
      },
      {
        key: 'Disability',
        label: 'Disability',
        type: 'string',
        choices: ["Yes","No","DeclinedToIdentify"],
        required: false,
        list: false,
        altersDynamicFields: false,
        helpText: 'Disability types'
      },
      {
        key: 'HomePhone',
        label: 'Home Phone',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
        helpText: "Employee's home telephone number."
      },
      {
        key: 'MobilePhone',
        label: 'Mobile Phone',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
        helpText: "Employee's mobile telephone number."
      },
      {
        key: 'HomeEmail',
        label: 'Email Address (personal)',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
        helpText: "The employee's personal email address."
      },
      {
        key: 'WorkEmail',
        label: 'Email Address (work)',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
        helpText: "The employee's work email address."
      },
      {
        key: 'PrimaryAddress',
        children: [
          {
            key: 'StreetLine1',
            label: 'Street 1',
            type: 'string',
            required: true,
            list: false,
            altersDynamicFields: false,
          },
          {
            key: 'StreetLine2',
            label: 'Street 2',
            type: 'string',
            required: false,
            list: false,
            altersDynamicFields: false,
          },
          {
            key: 'Suite',
            label: 'Suite',
            type: 'string',
            required: false,
            list: false,
            altersDynamicFields: false,
          },
          {
            key: 'City',
            label: 'City',
            type: 'string',
            required: false,
            list: false,
            altersDynamicFields: false,
          },
          {
            key: 'State',
            label: 'State',
            type: 'string',
            required: false,
            list: false,
            altersDynamicFields: false,
          },
          {
            key: 'ZipCode',
            label: 'Postal Code',
            type: 'string',
            required: true,
            list: false,
            altersDynamicFields: false,
          },
          {
            key: 'County',
            label: 'County',
            type: 'string',
            required: false,
            list: false,
            altersDynamicFields: false,
          },
          {
            key: 'Country',
            label: 'Country',
            type: 'string',
            required: false,
            list: false,
            altersDynamicFields: false,
          },
        ],
        label: 'Primary Address',
        required: true,
        altersDynamicFields: false,
      },
      {
        key: 'WorkLocation',
        label: 'Work Location',
        type: 'integer',
        dynamic: 'get_work_locations.name',
        required: false,
        list: false,
        altersDynamicFields: false,
        helpText: 'The name of the Work Location to associate with new hire.'
      },
      {
        key: 'DepartmentCode',
        label: 'Department',
        type: 'integer',
        dynamic: 'get_departments.code.description',
        required: true,
        list: false,
        altersDynamicFields: false,
        helpText: 'Department'
      },
      {
        key: 'JobTitle',
        label: 'Job Title',
        type: 'string',
        dynamic: 'get_job_titles.jobTitle',
        required: false,
        list: false,
        altersDynamicFields: false,
        helpText: "The employee's job title."
      },      
      {
        key: 'HireDate',
        label: 'Hire Date',
        type: 'datetime',
        default: 'today',
        required: true,
        list: false,
        altersDynamicFields: false,
        helpText: 'Date the employee was hired.'
      },
      {
        key: 'ReHireDate',
        label: 'Re-hire Date',
        type: 'datetime',
        default: 'today',
        required: false,
        list: false,
        altersDynamicFields: false,
        helpText: 'Date the employee was re-hired.'
      },
      {
        key: 'Status',
        label: 'Status',
        type: 'string',
        default: 'Active',
        choices: [
          'Active',
          'Deceased',
          'LongTermDisability',
          'ShortTermDisability',
          'Fmla',
          'LaidOff',
          'LeaveWithPay',
          'LeaveWithoutPay',
          'ThirdPartyPayable',
          'Resigned',
          'Retired',
          'Terminated',
          'WorkersCompensation',
        ],
        required: true,
        list: false,
        altersDynamicFields: false,
        helpText: 'Status'
      },
      {
        key: 'Flsa',
        label: 'FLSA Type',
        type: 'string',
        choices: [
          'HourlyExempt',
          'HourlyNonExempt',
          'SalaryExempt',
          'SalaryNonExempt',
        ],
        helpText: 'Fair Labor Standards Act (FLSA) employment values.',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'EmploymentType',
        label: 'Employment Type',
        type: 'string',
        default: 'Regular',
        choices: ['Casual','IndependentContractor','Regular','Seasonal','Temporary','Variable'],
        required: false,
        list: false,
        altersDynamicFields: false,
        helpText: 'Employment types'
      },
      {
        key: 'ManagerEmpId',
        label: "Manager",
        type: 'string',
        dynamic: 'get_managers.id.name',
        required: false,
        list: false,
        altersDynamicFields: false,
        helpText: "The employee's manager."
      },
      {
        key: 'PaygroupDescription',
        label: 'Paygroup',
        type: 'string',
        dynamic: 'get_paygroups.payGroupName.payGroupName',
        required: true,
        list: false,
        altersDynamicFields: false,
        helpText: 'Pay group'

      },
    ],
    sample: {
      Id: 'd63759d5-40cc-4ec2-98df-772342f1b974',
      Url: 'v1/myresources/resource?resourceID=d63759d5-40cc-4ec2-98df-772342f1b974',
    },
    outputFields: [
      { key: 'Id' },
      { key: 'Url' }
    ],
  },
  display: {
    description: 'Creates an employee record.',
    hidden: false,
    label: 'Create Employee',
  },
  key: 'create_employee',
  noun: 'Employee',
};
