const perform = async (z, bundle) => {
  const options = {
    url: `https://${bundle.authData.subdomain}.paycor.com/v1/employees/onboarding`,
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Accept: 'application/json',
      Authorization: `Bearer ${bundle.authData.access_token}`,
      'Ocp-Apim-Subscription-Key': bundle.authData.subscription_key,
    },
    body: {
      LegalEntityId: bundle.authData.legal_entity_id,
      FirstName: bundle.inputData.FirstName,
      LastName: bundle.inputData.LastName,
      PreferredName: bundle.inputData.PreferredName,
      Gender: bundle.inputData.Gender,
      VeteranStatus: bundle.inputData.VeteranStatus,
      Disability: bundle.inputData.Disability,
      Ethnicity: bundle.inputData.Ethnicity,
      Address1: bundle.inputData.Address1,
      Address2: bundle.inputData.Address2,
      City: bundle.inputData.City,
      State: bundle.inputData.State,
      Zip: bundle.inputData.Zip,
      CountryCode: bundle.inputData.CountryCode,
      MobilePhone: bundle.inputData.MobilePhone,
      HomePhone: bundle.inputData.HomePhone,
      HomeEmailAddress: bundle.inputData.HomeEmailAddress,
      WorkLocationId: bundle.inputData.WorkLocationId,
      DepartmentCode: bundle.inputData.DepartmentCode,
      JobTitle: bundle.inputData.JobTitle,
      StartDate: bundle.inputData.StartDate,
      BaseSalary: bundle.inputData.BaseSalary,
      SalaryFrequency: bundle.inputData.SalaryFrequency,
    },
  };

  return z.request(options).then((response) => {
    response.throwForStatus();
    const results = response.json;
    return results.ResourceUrl;
  });
};

module.exports = {
  key: 'onboard_employee',
  noun: 'Employee',
  display: {
    label: 'Onboard Employee',
    description: 'Creates an employee and related model entities using a single method.',
    hidden: false,
    important: true,
  },
  operation: {
    inputFields: [
      {
        key: 'FirstName',
        label: 'First Name',
        type: 'string',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'LastName',
        label: 'Last Name',
        type: 'string',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'PreferredName',
        label: 'Preferred Name',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'Gender',
        label: 'Gender',
        type: 'string',
        choices: ['Male','Female'],
        helpText: "The employee's gender.",
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'Ethnicity',
        label: 'Ethnicity',
        type: 'string',
        choices: ["AmerIndorAKNative","Asian","BlackorAfricanAmerican","HispanicorLatino","White","NatHIorOthPacIsland","TwoormoreRaces","DeclinedToIdentify"],
        helpText: "The employee's ethnicity.",
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'Veteran',
        label: 'Veteran',
        type: 'string',
        choices: ["Yes","No","DeclinedToIdentify"],
        required: false,
        list: false,
        altersDynamicFields: false,
        helpText: 'Veteran types'
      },
      {
        key: 'Disability',
        label: 'Disability',
        type: 'string',
        choices: ["Yes","No","DeclinedToIdentify"],
        required: false,
        list: false,
        altersDynamicFields: false,
        helpText: 'Disability types'
      },
      {
        key: 'HomePhone',
        label: 'Home Phone',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'MobilePhone',
        label: 'Mobile Phone',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'HomeEmailAddress',
        label: 'Email Address (home)',
        type: 'string',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      // {
      //   key: 'ExportedByEmailAddress',
      //   label: 'Email Address (exported)',
      //   type: 'string',
      //   required: false,
      //   list: false,
      //   altersDynamicFields: false,
      // },
      {
        key: 'Address1',
        label: 'Address 1',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'Address2',
        label: 'Address 2',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'City',
        label: 'City',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'State',
        label: 'State',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'Zip',
        label: 'Postal Code',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'CountryCode',
        label: 'Country Code',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'WorkLocationId',
        label: 'Work Location',
        type: 'string',
        dynamic: 'get_work_locations.id',
        required: false,
        list: false,
        altersDynamicFields: false,
        helpText: 'The name of the Work Location to associate with new hire.'
      },
      {
        key: 'DepartmentCode',
        label: 'Department',
        type: 'string',
        dynamic: 'get_departments.id.description',
        required: false,
        list: false,
        altersDynamicFields: false,
        helpText: 'Department'
      },
      {
        key: 'JobTitle',
        label: 'Job Title',
        type: 'string',
        // dynamic: 'get_job_titles.jobTitle',
        required: false,
        list: false,
        altersDynamicFields: false,
        helpText: "The employee's job title."
      },
      {
        key: 'StartDate',
        label: 'Start Date',
        type: 'datetime',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'BaseSalary',
        label: 'Base Salary',
        type: 'decimal',
        required: false,
        list: false,
        altersDynamicFields: false,
        helpText: "The employee's salary."
      },
      {
        key: 'SalaryFrequency',
        label: 'Salary Frequency',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
        helpText: "The payroll frequency."
      },
    ],
    sample: {
      Id: 'd63759d5-40cc-4ec2-98df-772342f1b974',
      Url: 'v1/myresources/resource?resourceID=d63759d5-40cc-4ec2-98df-772342f1b974',
    },
    outputFields: [{ key: 'Id' }, { key: 'Url' }],
    perform: perform,
  },
};
